# What message should the player receive if kicked?
kick-message: "&cYou have been kicked."
# How long to wait before kicking a player in seconds.
kick-delay: 0
# What message should the player receive if banned?
ban-message: "&cYou have been banned for %check%"
# How long to wait before banning a player in seconds.
ban-delay: 0
# How should a player banned? By NAME or IP
ban-type: NAME
# The ban length type when banning a player.
# Accepts: 'DAYS', 'YEARS', 'PERM' for permanent bans
ban-length-type: DAYS
# How long should a player be banned for?
ban-length: 30
# Should bans be broadcasted?
broadcast-ban: false
# If so, what should the message be?
broadcast-ban-message: "&c%player% was banned for %check%"
# The ban message to display to players with the permissions arc.violations
ban-message-to-violations: "%prefix% &9%player%&f will be banned for &c%check%&f in &c%time%&f seconds."
# If arc should monitor TPS and adjust check performance if TPS drops
tps-helper: true
# When TPS to this or below TPS helper will engage.
tps-lower-limit: 17
# The message to display when a violation occurs
violation-notify-message: "%prefix% &9%player%&f has violated check &c%check%&8(&c%level%&8)&7 %information%"
# The message to display when the sender has no permission for the /arc command.
arc-command-no-permission-message: "Unknown command. Type /help for help."
# The prefix to show in chat.
arc-prefix: "&8[&cArc&8]"
# The amount of time after a player leaves their violation data will be removed, in minutes.
violation-data-timeout: 30