# What message should the player receive if kicked?
kick-message: "&cYou have been kicked."
# How long to wait before kicking a player in seconds.
kick-delay: 0
# What message should the player receive if banned?
ban-message: "&cYou have been banned for %check%"
# How long to wait before banning a player in seconds.
ban-delay: 0
# How should a player banned? By NAME or IP
ban-type: NAME
# The ban length type when banning a player.
# Accepts: 'DAYS', 'YEARS', 'PERM' for permanent bans
ban-length-type: DAYS
# How long should a player be banned for?
ban-length: 30
# Should bans be broadcasted?
broadcast-ban: false
# If so, what should the message be?
broadcast-ban-message: "&c%player% was banned for %check%"
# If arc should monitor TPS and adjust check performance if TPS drops
tps-helper: true
# When TPS to this or below TPS helper will engage.
tps-lower-limit: 17
# The message to display when a violation occurs
violation-notify-message: "&8[&cArc&8] &9%player%&f has violated check &c%check%&8(&c%level%&8)&7 [%information%]"
# A example check to show off configuration options
example-check:
  # If this check is enabled
  enabled: true
  # If this check should cancel when a player fails
  # For example, attempting to fly will teleport the player back.
  cancel: true
  # When this check should start cancelling.
  # If the players violation level is greater than this the check will cancel.
  cancel-level: 0
  # If this check should notify players with the permission 'arc.violations'
  notify: true
  # Notifies players with the permission 'arc.violations' every time this number is
  # divisible by the violation level.
  # If this value is 1, the check will notify every time.
  # If this value is 2, the check will notify every time their violation level can be divided by 2.
  # If this value is 4, the check will notify every time their violation level can be divided by 4.
  # For example if the value is 4, you would see "Failed VL: (4)" .. "Failed VL: (8)" ... "Failed VL: (12)".. etc
  notify-every: 1
  # If this check should ban.
  ban: true
  # When the player violation level reaches this number the player will be banned.
  ban-level: 100
  # If this check should kick.
  kick: true
  # When the player violation level reaches this number the player will be kicked.
  kick-level: 50
  # An example value
  example-check-value: 0.5