main: arc.Arc
name: Arc
version: 2.5-pre1
description: An anticheat for 1.8.8, 1.12.2 and 1.16.5
author: Vrekt
depend:
  - ProtocolLib
api-version: 1.13

permissions:
  arc.commands.toggleviolations:
    description: Allows the player to toggle their violations.
  arc.commands.cancelban:
    description: Allows the player to cancel bans.
  arc.commands.reloadconfig:
    description: Allows the player to reload Arcs configuration.
  arc.commands.base:
    description: Allows the player to execute /arc
  arc.commands.all:
    description: Allows the player to use all Arc commands.
  arc.commands.summary:
    description: Allows the player to access player summary information.
  arc.commands.timings:
    description: Allows the player to view timings information.
  arc.commands.exempt:
    description: Allows the player to exempt others or themselves.
  arc.commands.debug:
    description: Allows the player to toggle the debug messages.
  arc.bypass:
    default: false
    description: Allows the player to bypass all Arc checks.
    children:
      arc.bypass.moving:
        default: false
        description: Allows the player to bypass all Moving checks.
        children:
          arc.bypass.moving.morepackets:
            description: Allows the player to bypass the MorePackets check.
          arc.bypass.moving.nofall:
            description: Allows the player to bypass the NoFall check.
          arc.bypass.moving.jesus:
            description: Allows the player to bypass the Jesus check.
          arc.bypass.moving.speed:
            description: Allows the player to bypass the Speed check.
          arc.bypass.moving.flight:
            description: Allows the player to bypass the Flight check.
            children:
              arc.bypass.moving.flight.boatfly:
                description: Allows the player to bypass the Flight BoatFly check.
              arc.bypass.moving.flight.elytrafly:
                description: Allows the player to bypass the Flight ElytraFly check.
      arc.bypass.player:
        default: false
        description: Allows the player to bypass all Player checks.
        children:
          arc.bypass.player.regeneration:
            description: Allows the player to bypass the Regeneration check
          arc.bypass.player.fastuse:
            description: Allows the player to bypass the FastUse check
            children:
              arc.bypass.player.fastuse.fastconsume:
                description: Allows the player to bypass the FastUse FastConsume check.
              arc.bypass.player.fastuse.fastbow:
                description: Allows the player to bypass the FastUse FastBow check.
      arc.bypass.network:
        default: false
        description: Allows the player to bypass all network/packet checks.
        children:
          arc.bypass.network.payloadfrequency:
            description: Allows the player to bypass payload packet checks.
          arc.bypass.network.swingfrequency:
            description: Allows the player to bypass the swing packet checks.
      arc.bypass.combat:
        default: false
        description: Allows the player to bypass all combat checks.
        children:
          arc.bypass.combat.criticals:
            description: Allows the player to bypass the criticals check.
          arc.bypass.combat.reach:
            description: Allows the player to bypass the reach check.
          arc.bypass.combat.noswing:
            description: Allows the player to bypass the NoSwing check.
          arc.bypass.combat.killaura:
            description: Allows the player to bypass all killaura checks.
            children:
              arc.bypass.combat.killaura.direction:
                description: Allows the player to bypass KillAura direction check.
              arc.bypass.combat.killaura.attackspeed:
                description: Allows the player to bypass the KillAura attackspeed check.
      arc.bypass.blockbreak:
        description: Allows the player to bypass all block break checks.
        children:
          arc.bypass.blockbreak.reach:
            description: Allows the player to bypass the block break reach check.
          arc.bypass.blockbreak.noswing:
            description: Allows the player to bypass the block break noswing check.
      arc.bypass.blockplace:
        description: Allows the player to bypass all block place checks.
        children:
          arc.bypass.blockplace.reach:
            description: Allows the player to bypass the block place reach check.
          arc.bypass.blockplace.noswing:
            description: Allows the player to bypass the block place noswing check.
      arc.bypass.blockinteract:
        description: Allows the player to bypass all block interact checks.
        children:
          arc.bypass.blockinteract.reach:
            description: Allows the player to bypass the block interact reach check.
          arc.bypass.blockinteract.noswing:
            description: Allows the player to bypass the block interact noswing check.
      arc.bypass.block:
        default: false
        description: Allows the player to bypass all block checks.
        children:
          arc.bypass.block.nuker:
            description: Allows the player to bypass the Nuker check.

  arc.violations:
    description: Allows the player to view player violations as they come in.

commands:
  arc:
    description: The base command for managing Arc.