main: arc.Arc
name: Arc
version: 1.0.6
description: Arc is an anticheat built for legacy verisons of Spigot.
author: Vrekt
depend:
  - ProtocolLib

permissions:
  arc.commands.toggleviolations:
    description: Allows the player to toggle their violations.
  arc.commands.cancelban:
    description: Allows the player to cancel bans.
  arc.commands.reloadconfig:
    description: Allows the player to reload Arcs configuration.
  arc.commands.base:
    description: Allows the player to execute /arc
  arc.commands.all:
    description: Allows the player to use all Arc commands.
  arc.bypass:
    description: Allows the player to bypass all Arc checks.
    children:
      arc.bypass.moving:
        description: Allows the player to bypass all Moving checks.
        children:
          arc.bypass.moving.morepackets:
            description: Allows the player to bypass the MorePackets check.
          arc.bypass.moving.nofall:
            description: Allows the player to bypass the NoFall check.
      arc.bypass.player:
        description: Allows the player to bypass all Player checks.
        children:
          arc.bypass.player.regeneration:
            description: Allows the player to bypass the Regeneration check
      arc.bypass.network:
        description: Allows the player to bypass all network/packet checks.
        children:
          arc.bypass.network.payloadfrequency:
            description: Allows the player to bypass payload packet checks.
          arc.bypass.network.swingfrequency:
            description: Allows the player to bypass the swing packet checks.
      arc.bypass.combat:
        description: Allows the player to bypass all combat checks.
        children:
          arc.bypass.combat.criticals:
            description: Allows the player to bypass the criticals check.
  arc.violations:
    description: Allows the player to view player violations as they come in.
    children:
      arc.violations.debug:
        description: Allows the player to view extra debug information with violations.
  arc.administrator:
    description: Allows the player permission to manage Arc.
    default: false

commands:
  arc:
    description: The base command for managing Arc.